eleisaun/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admeleisauntl/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
]

website/urls.py
from django.urls import path
from . import views
#from .views import room_create, room_list, room_delete, room_update

urlpatterns = [
    # FBV Urls
    path('', views.dashboard, name='dashboard'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from logging.config import IDENTIFIER
from django.shortcuts import render, redirect, get_object_or_404
from apuramentu.models import *
from django.db.models import Sum





def dashboard(request):
    sentru_votasaun_id = request.GET.get('fatin_vota')
    ronda = request.GET.get('volta_dahira')
    print('Ronda', ronda)
    context = get_context_data_for_timor_leste(sentru_votasaun_id, ronda)

    if ronda == '6':
        template_name = 'index-first.html'
    else:
        template_name = 'index.html'

    if not sentru_votasaun_id is None and not ronda is None:
        print('not none')
        if int(sentru_votasaun_id) <= 18:
            print('under 18')
            context = get_context_data(sentru_votasaun_id, ronda)
        elif int(sentru_votasaun_id) == 19:
            print('19')
            context = get_context_data_for_timor_leste(sentru_votasaun_id, ronda)
        elif int(sentru_votasaun_id) == 20:
            print('20')
            context = get_context_data_for_nivel('Natl', sentru_votasaun_id, ronda)
        else:
            print('21')
            context = get_context_data_for_nivel('Intl', sentru_votasaun_id, ronda)

    if request.htmx and (ronda=='6' or ronda is None):
        template_name = 'partials/first-election-chart.html'
        print('first round')
        return render(request, template_name, context)
        
    if request.htmx and (ronda=='7' or ronda is None):
        template_name = 'partials/second-election-chart.html'
        print('second round')
        return render(request, template_name, context)

    return render(request, template_name, context)



def get_context_data(id, ronda):
    print('data')
    print(ronda)
    dahira_label = ''
    apuramentu = ''
    somatoriu_votu = ''
    sentru_votasaun = "Timor-Leste"
    sentru_votasaun_hotu = SentruVotasaun.objects.all()
    jrh_total_votu = 50
    fgl_total_votu = 50
    jrh_persentajen = '50%'
    fgl_persentajen = '50%'
    
    sentru_votasaun = SentruVotasaun.objects.get(id=id)
    sentru_votasaun_hotu = SentruVotasaun.objects.all()

    if ronda == '6': 
        dahira_label = 'Volta Dahuluk (1)' 
        apuramentu = Apuramentu.objects.filter(sentru_votasaun=id, eleisaun=ronda).order_by('-total_votu')
        somatoriu_votu = Apuramentu.objects.filter(sentru_votasaun=id, eleisaun=ronda).aggregate(soma=Sum('total_votu'))['soma']
    else: 
        dahira_label = 'Volta Daruak (2)'
        jrh_total_votu = Apuramentu.objects.filter(eleisaun=ronda, sentru_votasaun=id, kandidatu='14').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        fgl_total_votu = Apuramentu.objects.filter(eleisaun=ronda, sentru_votasaun=id, kandidatu='6').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        try:
            jrh_persentajen = (jrh_total_votu/(jrh_total_votu+fgl_total_votu))*100
            fgl_persentajen = (fgl_total_votu/(jrh_total_votu+fgl_total_votu))*100
        except:
            jrh_total_votu = 1
            fgl_total_votu = 1
            jrh_persentajen = '0'
            fgl_persentajen = '0'

    context = {
        'apuramentu': apuramentu,
        'sentru_votasaun': sentru_votasaun,
        'somatoriu_votu': somatoriu_votu,
        'sentru_votasaun_hotu': sentru_votasaun_hotu,
        'sentru_id': id,
        'dahira_label': dahira_label,
        'jrh_total_votu': jrh_total_votu,
        'fgl_total_votu': fgl_total_votu,
        'jrh_persentajen': jrh_persentajen,
        'fgl_persentajen': fgl_persentajen,
        'ronda': ronda,
    }

    return context



def get_context_data_for_timor_leste(id, ronda):
    print('tl')
    dahira_label = ''
    apuramentu = ''
    somatoriu_votu = ''
    sentru_votasaun = "Timor-Leste"
    sentru_votasaun_hotu = SentruVotasaun.objects.all()
    jrh_total_votu = 50
    fgl_total_votu = 50
    jrh_persentajen = '50%'
    fgl_persentajen = '50%'


    if ronda == '6': 
        dahira_label = 'Volta Dahuluk (1)'
        apuramentu = Apuramentu.objects.filter(eleisaun=ronda).values('kandidatu').order_by('-total_votu').annotate(total_votu=Sum('total_votu'))
        somatoriu_votu = Apuramentu.objects.filter(eleisaun=ronda).aggregate(soma=Sum('total_votu'))['soma']
    else: 
        dahira_label = 'Volta Daruak (2)'
        jrh_total_votu = Apuramentu.objects.filter(eleisaun=ronda, kandidatu='14').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        fgl_total_votu = Apuramentu.objects.filter(eleisaun=ronda, kandidatu='6').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        try:
            jrh_persentajen = (jrh_total_votu/(jrh_total_votu+fgl_total_votu))*100
            fgl_persentajen = (fgl_total_votu/(jrh_total_votu+fgl_total_votu))*100
        except:
            jrh_total_votu = 1
            fgl_total_votu = 1
            jrh_persentajen = '0'
            fgl_persentajen = '0'

    context = {
        'apuramentu': apuramentu,
        'sentru_votasaun': sentru_votasaun,
        'somatoriu_votu': somatoriu_votu,
        'sentru_votasaun_hotu': sentru_votasaun_hotu,
        'sentru_id': id,
        'dahira_label': dahira_label,
        'jrh_total_votu': jrh_total_votu,
        'fgl_total_votu': fgl_total_votu,
        'jrh_persentajen': jrh_persentajen,
        'fgl_persentajen': fgl_persentajen,
        'ronda': ronda,
    }

    return context



def get_context_data_for_nivel(nivel, id, ronda):
    print('nivel')
    dahira_label = dahira_label
    apuramentu = ''
    somatoriu_votu = ''
    sentru_votasaun = "Timor-Leste"
    sentru_votasaun_hotu = SentruVotasaun.objects.all()
    jrh_total_votu = 50
    fgl_total_votu = 50
    jrh_persentajen = '50%'
    fgl_persentajen = '50%'
    
    if nivel == 'Natl': sentru_votasaun = "Nasionál" 
    else: sentru_votasaun = "Internasionál"

    if ronda == '6': 
        dahira_label = 'Volta Dahuluk (1)'
        apuramentu = Apuramentu.objects.filter(sentru_votasaun__nivel=nivel, eleisaun=ronda).values('kandidatu').order_by('-total_votu').annotate(total_votu=Sum('total_votu'))
        somatoriu_votu = Apuramentu.objects.filter(sentru_votasaun__nivel=nivel, eleisaun=ronda).aggregate(soma=Sum('total_votu'))['soma']
    else: 
        dahira_label = 'Volta Daruak (2)'
        jrh_total_votu = Apuramentu.objects.filter(eleisaun=ronda, sentru_votasaun__nivel=nivel, kandidatu='14').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        fgl_total_votu = Apuramentu.objects.filter(eleisaun=ronda, sentru_votasaun__nivel=nivel, kandidatu='6').aggregate(total_votu_apuradu=Sum('total_votu'))['total_votu_apuradu']
        
        try:
            jrh_persentajen = (jrh_total_votu/(jrh_total_votu+fgl_total_votu))*100
            fgl_persentajen = (fgl_total_votu/(jrh_total_votu+fgl_total_votu))*100
        except:
            jrh_total_votu = 1
            fgl_total_votu = 1
            jrh_persentajen = '0'
            fgl_persentajen = '0'

    sentru_votasaun_hotu = SentruVotasaun.objects.all()

    context = {
        'apuramentu': apuramentu,
        'sentru_votasaun': sentru_votasaun,
        'somatoriu_votu': somatoriu_votu,
        'sentru_votasaun_hotu': sentru_votasaun_hotu,
        'sentru_id': id,
        'dahira_label': dahira_label,
        'jrh_total_votu': jrh_total_votu,
        'fgl_total_votu': fgl_total_votu,
        'jrh_persentajen': jrh_persentajen,
        'fgl_persentajen': fgl_persentajen,
        'ronda': ronda,
    }
    
    return context



# @api_view(['GET'])
# def getPeopleList(request):
#     people = People.objects.all()
#     serializer = PeopleSerializer(people, many=True)
#     return Response(serializer.data)

website/templates/index-first.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% endblock %}
{% block inject_css %}

{% endblock %}

{% block page_plugin_css %}
{% endblock %}

{% block content %}



<div class="content-wrapper">



  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Eleisaun Prezidensiál - Períodu 2022-2027</h4>
        <form class="form-sample" hx-get="{% url 'website:dashboard' %}" hx-target="#first-election-chart" hx-push-url="true">
          
          <div class="row mt-4">

            <div class="col-md-3">
              <div class="form-group row">
                <div class="col-sm-9">
                  <select class="form-control" name="volta_dahira">
                    <option value="7" data-select2-id="7" {% if ronda|add:0 == 7 %} selected {% endif %}>Volta Da-2</option>
                    <option value="6" data-select2-id="6" {% if ronda|add:0 == 6 %} selected {% endif %}>Volta Da-1</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="col-md-3">
              <div class="form-group row">
                <div class="col-sm-9">
                  <select class="form-control" name="fatin_vota">
                    <option value="19" data-select2-id="19" {% if sentru_id|add:0 == 19 %} selected {% endif %}>Timor-Leste</option>
                    <option value="20" data-select2-id="20" {% if sentru_id|add:0 == 20 %} selected {% endif %}>Nasionál</option>
                    <option value="21" data-select2-id="21" {% if sentru_id|add:0 == 21 %} selected {% endif %}>Internasionál</option>
                    {% for sentru in sentru_votasaun_hotu %}
                    <option value="{{ sentru.id }}" data-select2-id="{{ sentru.id }}" {% if sentru_id|add:0 == sentru.id %} selected {% endif %}>{{ sentru.fatin_votasaun }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>

            <div class="col-md-2">
              <button type="submit" class="btn btn-dark btn-md">Submit</button>
            </div>

          </div>
        </form>

        <div class="row">


          <div id="first-election-chart" class="col-md-12 mt-4">
            {% include 'partials/first-election-chart.html' with jrh_total_votu=jrh_total_votu fgl_total_votu=fgl_total_votu %}
          </div>


        </div>


      </div>
    </div>
  </div>
  

  <!-- container-scroller -->
{% endblock content %}
{% block script %}
   <!-- Custom js for this page -->
   {% block page_custom_js %}
    <script src="{% static 'vendors/js/dashboard.js' %}"></script>
    <!-- <script src="{% static 'vendors/other-charts/js/google-charts.js' %}"></script> -->
   {% endblock %}
   <!-- End custom js for this page -->
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% endblock %}
{% block inject_css %}

{% endblock %}

{% block page_plugin_css %}
{% endblock %}

{% block content %}



<div class="content-wrapper">



  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Eleisaun Prezidensiál - Períodu 2022-2027</h4>
        <form class="form-sample" hx-get="{% url 'website:dashboard' %}" hx-target="#first-election-chart" hx-push-url="true">
          
          <div class="row mt-4">

            <div class="col-md-3">
              <div class="form-group row">
                <div class="col-sm-9">
                  <select class="form-control" name="volta_dahira">
                    <option value="7" data-select2-id="7" {% if ronda|add:0 == 7 %} selected {% endif %}>Volta Da-2</option>
                    <option value="6" data-select2-id="6" {% if ronda|add:0 == 6 %} selected {% endif %}>Volta Da-1</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="col-md-3">
              <div class="form-group row">
                <div class="col-sm-9">
                  <select class="form-control" name="fatin_vota">
                    <option value="19" data-select2-id="19" {% if sentru_id|add:0 == 19 %} selected {% endif %}>Timor-Leste</option>
                    <option value="20" data-select2-id="20" {% if sentru_id|add:0 == 20 %} selected {% endif %}>Nasionál</option>
                    <option value="21" data-select2-id="21" {% if sentru_id|add:0 == 21 %} selected {% endif %}>Internasionál</option>
                    {% for sentru in sentru_votasaun_hotu %}
                    <option value="{{ sentru.id }}" data-select2-id="{{ sentru.id }}" {% if sentru_id|add:0 == sentru.id %} selected {% endif %}>{{ sentru.fatin_votasaun }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>

            <div class="col-md-2">
              <button type="submit" class="btn btn-dark btn-md">Submit</button>
            </div>

          </div>
        </form>

        <div class="row">


          <div id="first-election-chart" class="col-md-12 mt-4">
            {% include 'partials/second-election-chart.html' with jrh_total_votu=jrh_total_votu fgl_total_votu=fgl_total_votu %}
          </div>


        </div>


      </div>
    </div>
  </div>
  

  <!-- container-scroller -->
{% endblock content %}
{% block script %}
   <!-- Custom js for this page -->
   {% block page_custom_js %}
    <script src="{% static 'vendors/js/dashboard.js' %}"></script>
    <!-- <script src="{% static 'vendors/other-charts/js/google-charts.js' %}"></script> -->
   {% endblock %}
   <!-- End custom js for this page -->
{% endblock %}